variables:
  backendImageName: testouilleBackend
  frontendImageName: testouilleFrontend
  docsImageName: testouilleDocs
  tutorialImageName: testouilleTutorial
  benchmarkingImageName: testouilleBenchmarking

trigger:
- feature-azure-pipeline

pool:
  vmImage: "ubuntu-16.04"

steps:
- script: docker build -t $(backendImageName) ./backend
- script: docker build -t $(frontendImageName) ./frontend
- script: docker build -t $(docsImageName) ./docs
- script: docker build -t $(tutorialImageName) ./docs/tutorial
- script: docker build -t $(benchmarkingImageName) ./benchmarking
    

#- stage: DockerCompose
#  displayName: Test deployment
#  dependsOn: DockerBuilds
#  condition: succeeded('DockerBuilds')
#  jobs:
#  - job: dockerComposeversion
  
