variables:
  backendImageName: quay.io/anonlink-test #data61/anonlink-entity-service-backend
  frontendImageName: quay.io/anonlink-test #data61/anonlink-entity-service-frontend
  docsImageName: quay.io/anonlink-test #data61/anonlink-entity-service-docs
  tutorialImageName: quay.io/anonlink-test #data61/anonlink-entity-service-tutorial
  benchmarkingImageName: quay.io/anonlink-test #data61/anonlink-entity-service-benchmarking

trigger:
- feature-azure-pipeline

pool:
  vmImage: "ubuntu-16.04"

steps:
- bash: |
    tag = $(echo $(Build.SourceBranch) | tr [:upper:] [:lower:] | tr -d -c [a-z])
    docker build -t $(backendImageName):$tag ./backend
- bash: |
    tag = $(echo $(Build.SourceBranch) | tr [:upper:] [:lower:] | tr -d -c [a-z])
    docker build -t $(frontendImageName):$tag ./frontend
#- bash: |
#    tag = echo $(Build.SourceBranch) | tr [:upper:] [:lower:] | tr -d -c [a-z]   
#    docker build -t $(docsImageName):$tag ./docs
#- bash: |
#    tag = echo $(Build.SourceBranch) | tr [:upper:] [:lower:] | tr -d -c [a-z]
#    docker build -t $(tutorialImageName):$tag ./docs/tutorial
- bash: |
    tag = $(echo $(Build.SourceBranch) | tr [:upper:] [:lower:] | tr -d -c [a-z])
    docker build -t $(benchmarkingImageName):$tag ./benchmarking
    

#- stage: DockerCompose
#  displayName: Test deployment
#  dependsOn: DockerBuilds
#  condition: succeeded('DockerBuilds')
#  jobs:
#  - job: dockerComposeversion
  
