variables:
  backendImageName: quay.io/anonlink-test #data61/anonlink-app
  frontendImageName: data61/anonlink-nginx
  docsImageName: quay.io/anonlink-test #data61/anonlink-entity-service-docs
  tutorialImageName: quay.io/anonlink-test #data61/anonlink-entity-service-tutorial
  benchmarkingImageName: quay.io/anonlink-test #data61/anonlink-benchmarking

trigger:
- feature-azure-pipeline

pool:
  vmImage: "ubuntu-16.04"

steps:
- script: |
    echo "$(Build.BuildID)$(Build.SourceBranch)" | tr [:upper:] [:lower:] | tr -cd [a-z] | xargs -I@ echo "##vso[task.setvariable variable=dockertag]@"
    echo "$(Build.BuildID)$(Build.SourceBranch)"
- script: |
    docker login -u $(dockerHubId) -p $(dockerHubPassword)
#- script: |
#    docker build -t $(backendImageName):$(dockertag) ./backend
#    docker push $(backendImageName):$(dockertag)
- script: |
    docker build -t $(frontendImageName):$(dockertag) ./frontend
    docker push $(frontendImageName):$(dockertag)
#- script: |  
#    docker build -t $(docsImageName):$(dockertag) ./docs
#- script: |
#    docker build -t $(tutorialImageName):$(dockertag) ./docs/tutorial
#- script: |
#    docker build -t $(benchmarkingImageName):$(dockertag) ./benchmarking
    

#- stage: DockerCompose
#  displayName: Test deployment
#  dependsOn: DockerBuilds
#  condition: succeeded('DockerBuilds')
#  jobs:
#  - job: dockerComposeversion
  
