variables:
  backendImageName: data61/anonlink-entity-service-backend
  frontendImageName: data61/anonlink-entity-service-frontend
  docsImageName: data61/anonlink-entity-service-docs
  tutorialImageName: data61/anonlink-entity-service-tutorial
  benchmarkingImageName: data61/anonlink-entity-service-benchmarking

trigger:
- feature-azure-pipeline

pool:
  vmImage: "ubuntu-16.04"

steps:
- script: docker build -t $(backendImageName)-$(Build.BuildID) ./backend
- script: docker build -t $(frontendImageName)-$(Build.BuildID) ./frontend
- script: docker build -t $(docsImageName)-$(Build.BuildID) ./docs
- script: docker build -t $(tutorialImageName)-$(Build.BuildID) ./docs/tutorial
- script: docker build -t $(benchmarkingImageName)-$(Build.BuildID) ./benchmarking
    

#- stage: DockerCompose
#  displayName: Test deployment
#  dependsOn: DockerBuilds
#  condition: succeeded('DockerBuilds')
#  jobs:
#  - job: dockerComposeversion
  
