# Template to login into dockerhub, build a docker image and push it.

#jobName should only include alphanumeric values and '_'.
parameters:
  folder: ''
  imageName: ''
  jobName: ''
  extraJobs: []

jobs:
- job: ${{ jobName }}
  displayName: Building ${{ parameters.imageName }}
  pool:
    vmImage: "ubuntu-16.04"

  steps:
  - script: |
      sourceBranch="$(Build.SourceBranch)"; echo ${sourceBranch##*/} | tr [:upper:] [:lower:] | tr -cd [a-z] | xargs -I@ echo "##vso[task.setvariable variable=dockertag]@"
  - script: |
      docker login -u $(dockerHubId) -p $(dockerHubPassword)
  - script: |
      docker build -t ${{ parameters.imageName }}:$(dockertag) ${{ parameters.folder }}
      docker push ${{ parameters.imageName }}:$(dockertag)
      
# Updated from the documentation https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
# The idea being able to define jobs depending on the creation of the previous image.
- ${{ each job in parameters.jobs }}: # Then do each job
  - ${{ each pair in job }}:          # Insert all properties other than "dependsOn"
      ${{ if ne(pair.key, 'dependsOn') }}:
        ${{ pair.key }}: ${{ pair.value }}
    dependsOn:                        # Inject dependency
    - ${{ jobName }}
    - ${{ if job.dependsOn }}:
      - ${{ job.dependsOn }}
