version: '3.4'
services:


  tests:
    image: data61/anonlink-app:${TAG:-latest}
    environment:
      - ENTITY_SERVICE_URL=http://nginx:8851/api/v1
      - INITIAL_DELAY=20
    entrypoint: /bin/sh -c "wait4ports nginx:8851 ; python -m pytest entityservice/tests -x"
    depends_on:
      - db
      - redis
      - worker
      - nginx
      
  benchmark:
    image: data61/anonlink-benchmark:${TAG:-latest}
    environment:
      - SERVER=http://nginx:8851
      - DATA_PATH=/cache
      - EXPERIMENT=/cache/linkage-bench-cache-experiments.json
      - RESULTS_PATH=/app/results.json
    volumes:
      - linkage-benchmark-data:/cache
    depends_on:
      - db
      - redis
      - worker
      - nginx
      
volumes:
  linkage-benchmark-data:
